api_version = "2025-01"

[[extensions]]
type = "ui_extension"
name = "discount-notification"
handle = "discount-notification"

[[extensions.targeting]]
target = "purchase.checkout.block.render"
module = "./src/Checkout.jsx"

[extensions.capabilities]
network_access = true
api_access = true

[extensions.settings]
[[extensions.settings.fields]]
key = "discount_message"
type = "single_line_text_field"
name = "Discount Message"
description = "Message to show when discount is applied"

[[extensions.settings.fields]]
key = "show_notification"
type = "boolean"
name = "Show Notification"
description = "Show discount notification banner"

[[extensions.settings.fields]]
key = "auto_apply"
type = "boolean"
name = "Auto Apply Discount"
description = "Automatically apply available discounts"
